### ISSUE TITLE
vite unplugin-vue-components 打包错误

### ISSUE THREAD

**Issue by bzw1204** [fudiwei/x.naive-ui#1]
这么写，ts报找不到声明错误
![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/c1a46dcb-62dd-43d2-a367-a7bf3a65c029)
打包报：
![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/8e0f7602-6c98-4f3f-ae38-b34a2675d722)

这么写ts不报错，但是打包提示
![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/34e683b2-6129-4f73-8166-4ef646d0bd3b)

![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/0576f254-12d4-4447-979f-9fabd2927db6)

**Comment by batchor** [comment]
Same thing here. I'm using npm.

**Comment by fudiwei** [comment]
版本是多少？另外贴一下 `tsconfig.json` 看看。

Which version are you using? BTW, please post `tsconfig.json`.

**Comment by bzw1204** [comment]
> 版本是多少？另外贴一下 `tsconfig.json` 看看。
> 
> Which version are you using? BTW, please post `tsconfig.json`.

![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/3b22edf5-04f0-43f9-ad35-3d8a235a5426)
![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/b9e2cb26-0a7c-4ea2-bc63-a31aa60971b2)

**Comment by fudiwei** [comment]
![image](https://github.com/fudiwei/x.naive-ui/assets/18504146/394e774f-71c4-4f6a-9fdc-8cb736c1cbed)

将该项的值设置为 `Bundler` 后再试试看。

Try to set `"moduleResolution"` to `"Bundler"` in tsconfig.json.

**Comment by bzw1204** [comment]
> ![image](https://user-images.githubusercontent.com/18504146/274611526-394e774f-71c4-4f6a-9fdc-8cb736c1cbed.png)
> 
> 将该项的值设置为 `Bundler` 后再试试看。
> 
> Try to set `"moduleResolution"` to `"Bundler"` in tsconfig.json.

![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/0b55de05-90e2-43ec-ada5-1be6e1c5ec92)
改为bundler后会报这个错，除非删除这个配置
![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/f6dce279-1925-4a8e-a7dc-ad89a4c0f8c1)

**Comment by fudiwei** [comment]
新发布了一个版本，保持 `"moduleResolution": "Bundler"` 配置不变，尝试升级看看。

Try to upgrade to v0.11.0 (keep `"moduleResolution": "Bundler"`).

**Comment by bzw1204** [comment]
> 新发布了一个版本，保持 `"moduleResolution": "Bundler"` 配置不变，尝试升级看看。
> 
> Try to upgrade to v0.11.0 (keep `"moduleResolution": "Bundler"`).

现在可以了
