### ISSUE TITLE
打包的是否可以把 index.d.ts声明放到dist中

### ISSUE THREAD

**Issue by bzw1204** [fudiwei/x.naive-ui#2]
在vite.config.ts中引入组件按需提示ts错误
![image](https://github.com/fudiwei/x.naive-ui/assets/9693637/6da844e5-3268-43c8-b333-4acbfee45c84)
是否可以修复

**Comment by fudiwei** [comment]
这个问题不是已经在 #1 解决了吗？

**Comment by bzw1204** [comment]
> 这个问题不是已经在 #1 解决了吗？

上个问题只是解决了打包的问题，这个是ts的错误提示，不影响使用，可以加 // @ts-ignore解决

**Comment by fudiwei** [comment]
`"moduleResolution": "Bundler"` 也是报错的吗？你现在项目用的 TS 的版本是多少？

**Comment by bzw1204** [comment]
> `"moduleResolution": "Bundler"` 也是报错的吗？你现在项目用的 TS 的版本是多少？

5.2.2

**Comment by bzw1204** [comment]
> `"moduleResolution": "Bundler"` 也是报错的吗？你现在项目用的 TS 的版本是多少？

有同事给改掉了，ε=(´ο｀*)))唉
