### ISSUE TITLE
表格render-filter

### ISSUE THREAD

**Issue by batsx** [fudiwei/x.naive-ui#3]
表格render-filter怎么使用？

**Comment by batsx** [comment]
表格是否支持官方所有API？

**Comment by fudiwei** [comment]
> 表格是否支持官方所有API？

有属性透传，兼容官方所有 Props + Events + Slots。

**Comment by batsx** [comment]
我在使用render-filter的时候无效，可否添加demo代码

**Comment by fudiwei** [comment]
> 我在使用render-filter的时候无效，可否添加demo代码

手头现在没环境，你可以先贴一下你现在是怎么写的。
