### ISSUE TITLE
能不能改改select组件

### ISSUE THREAD

**Issue by surge-squirrel** [fudiwei/x.naive-ui#4]

**Comment by surge-squirrel** [comment]
就是select单选并且可搜索情况下
当我选中了一个值以后
我再次点击
我想可以随意的选中，已经被选中的值的label
但是他现在点了以后就变成placeholder了没办法任意选中

就是想变成input框一样，光标可以移动到label的任意位置，可以任意的添加文字，删除文字，复制文字
这样就可以接着继续搜索

举个例子
我第一次搜索了美丽
然后我选择了美丽的花
然后我再次点击的时候
我就可以在美丽的花的基础上去添加文字继续搜索
比如我继续输入‘很好’
然后这个时候搜索出来'美丽的花很好看'
我没必要重新输入‘美丽的花很好’

而且我也可以直接复制‘美丽的花’然后粘贴到别的地方使用

**Comment by fudiwei** [comment]
理解了你的需求。

但本库的目标仅仅是为了给 Naive-UI 提供 Slot 插槽或 Template 模板式的写法支持，既不会提供新的组件、也不会破坏原有组件的表现形式或 API。

你应该到 https://github.com/tusen-ai/naive-ui/ 社区中提出 Feature Request。

**Comment by surge-squirrel** [comment]
好 谢谢
