### ISSUE TITLE
可否为 XNTree 的 slot render-prefix 添加 expanded 参数？

### ISSUE THREAD

**Issue by transtone** [fudiwei/x.naive-ui#5]
可否为 XNTree 的 slot render-prefix 添加 expanded 参数？
这样就方便修改前缀图标了，比如文件夹的关闭与打开。

https://www.naiveui.com/zh-CN/os-theme/components/tree#file-tree.vue

**Comment by fudiwei** [comment]
这些 Slot 最后还是会转换成 Props 的形式传给 NTree，而它原本的 Props 里 `render-prefix` 签名是这样的：

```typescript
(info: { option: TreeOption, checked: boolean, selected: boolean }) => VNodeChild
```

所以你应该先给 naive-ui 仓库提个 Feature Request，要求它那儿增加 `expanded` 这个参数，我这里可以跟进。但我自己没法添加这个，否则就有一致性问题了。

---

现在你要想实现这个需求倒也不是没有办法，你可以用 `expanded-keys` 这个 Props “中转”处理一下 —— 判断 `option.key` 是否在 `expanded-keys` 里就可以了。

**Comment by transtone** [comment]
>现在你要想实现这个需求倒也不是没有办法，你可以用 expanded-keys 这个 Props “中转”处理一下 —— 判断 option.key 是否在 expanded-keys 里就可以了。

多谢回复。当前正是使用 expanded-keys.includes(option.key) 判断的。如果有 expanded 参数会更简单。
