### ISSUE TITLE
数据表格 XNDataTable 问题

### ISSUE THREAD

**Issue by transtone** [fudiwei/x.naive-ui#8]
文档中的这个示例：https://github.com/fudiwei/x.naive-ui/blob/main/docs/zh-CN/Component_DataTable.md#scoped-slots

运行时有下列问题：
1. 点击行选择按钮报错：`warn.mjs:9  [naive/data-table]: fail to get row data with key undefined`
2. 控制台不断出现警告：`[Vue warn]: Invalid prop: type check failed for prop "rowKey". Expected String | Number, got Undefined  
  at <DataTableBodyCheckbox key=1 rowKey=undefined disabled=false  ... > `
3. 表头显示为：`Column () => { const slot = getVSlot(ctxSlots, "render-column"); const params = { column }; const vnodes = slot === null || slot === void 0 ? void 0 : slot(params); if (!isEmptyVNode(vnodes)) { return vnodes; } else if (typeof fallback === "function") { return fallback(column); } else { return fallback; } }`

![1713660676574](https://github.com/fudiwei/x.naive-ui/assets/46688/be1e5494-3f89-4885-81ca-cbf35d2b3550)

**Comment by fudiwei** [comment]
给表格设置下 `row-key` 看看。

> https://www.naiveui.com/zh-CN/os-theme/components/data-table
> 
> ![image](https://github.com/fudiwei/x.naive-ui/assets/18504146/c3d1a131-25c9-4c45-b90d-e6dac7ad36d8)

**Comment by transtone** [comment]
data 加上key
```js
const data = [
  { key: 1, name: 'Athos', age: 20 },
  { key: 2, name: 'Porthos', age: 19 },
  { key: 3, name: 'Aramis', age: 18 },
]
```
问题1，2解决了，警告没有了。表头显示错误要怎么解决？

**Comment by fudiwei** [comment]
奇怪了……

你跑下 demo 看看表格的前两个用例（基础用法、自定义渲染列头）显示是否正常？

**Comment by transtone** [comment]
第一个例子 https://github.com/fudiwei/x.naive-ui/blob/main/docs/zh-CN/Component_DataTable.md#template-style 正常。
```vue
    <x-n-data-table :data="data">
      <x-n-data-table-column type="selection" />
      <x-n-data-table-column key="no" title="NO.">
        <template #render-cell="{ rowIndex }">
          <div>{{ rowIndex + 1 }}</div>
        </template>
      </x-n-data-table-column>
      <x-n-data-table-column key="name" title="Name" />
      <x-n-data-table-column key="age" title="Age" />
      <x-n-data-table-column key="actions" title="Actions">
        <template #render-cell="{ column, rowData, rowIndex }">
          <button>{{ 'Say hello to ' + rowData.name }}</button>
        </template>
      </x-n-data-table-column>
    </x-n-data-table>
```

直接使用也正常：
```vue
    <n-data-table :columns="columns" :data="data" />
```
把 slot 去掉直接用也正常：
```vue
    <x-n-data-table :columns="columns" :data="data" />
```

============

有这个 slot 就出现上面的情况：
```vue
      <template #render-column="{ column }">
        <div>{{ 'Column ' + column.title }}</div>
      </template>
```

**Comment by fudiwei** [comment]
我是指 demo 项目里的用例，不是文档里的示例：

> https://github.com/fudiwei/x.naive-ui/blob/main/README.md#%E7%A4%BA%E4%BE%8B%E9%A1%B9%E7%9B%AE

前两个用例我记得都有 `render-column`。

**Comment by transtone** [comment]
https://github.com/fudiwei/x.naive-ui/blob/main/demo/views/components/data-table/sample-basic/demo.vue
这个没有 render-column
```vue
      <x-n-data-table :columns="columns" :data="data" :bordered="false">
            <template #render-cell="{ column, rowData, rowIndex }: DataTableRenderCellParams<Song>">
                <template v-if="column.key === 'no'">
                    {{ rowIndex + 1 }}
                </template>

                <template v-else-if="column.key === 'actions'">
                    <n-button size="small" strong tertiary @click="handleClickPlay(rowData)">Play</n-button>
                </template>
            </template>
        </x-n-data-table>
```

https://github.com/fudiwei/x.naive-ui/blob/main/demo/views/components/data-table/sample-column/demo.vue 这个可以用：
```vue
    <x-n-data-table :columns="columns" :data="data">
      <template #render-column="{ column }">
        <template v-if="column.key === 'name'">
          <n-tooltip>
            <template #trigger>
              <n-gradient-text :size="24" type="danger">Name</n-gradient-text>
            </template>
            Tooltip Content
          </n-tooltip>
        </template>

        <template v-else-if="column.key === 'age'">
          <n-gradient-text :size="20" type="info">Age</n-gradient-text>
        </template>
      </template>
    </x-n-data-table>
```
![1713664123973](https://github.com/fudiwei/x.naive-ui/assets/46688/c4368e23-6b71-46b9-9174-918a97cf73e7)

**Comment by transtone** [comment]
破案了， column 中只有 key，没有 title !

![1713664453661](https://github.com/fudiwei/x.naive-ui/assets/46688/5f599f2b-a797-4ffa-94ff-b7f8a2744205)

**Comment by fudiwei** [comment]
啊这……那我大概知道问题在哪了 😕

`render-column` 里为了支持插槽，已经在 setup 阶段把 `title` 转换成了 `(column: TableColumn) => VNodeChild` 的 JSX Function 形式了。所以 template 里 `'' + column.title` 得到的是这个 Function toString() 的一个字符串。（因为它是个 Function，所以你截图里它不会被 JSON 序列化显示出来，而不是没有 `title`）

最简单的改法是要么就别用插槽，如果用插槽的话就不要再用 `title` 这个属性了：

```diff
const columns = [
-  { key: "foo", title: "foo" }
+  { key: "foo", name: "foo" }
]

<x-n-data-table :columns="columns">
  <template #render-column="{ column }">
-    {{ 'col ' + column.title }}
+    {{ 'col ' + column.name }}
  </template>
</x-n-data-table>
```

P.S. 家里电脑没环境，徒手写的，应该能看懂意思。

---

等有空儿了我琢磨琢磨怎么能在支持插槽的同时保留 `title` 属性…… 😂

**Comment by transtone** [comment]
倒不是什么大问题，换个用法一样用。
原来以为只有 key ，你这么一说，我又加了几个属性进去，发现只有 title 不见了。

column 数据：
```js
    const columns = [
        { type: 'selection' },
        { key: 'no', title: 'NO.' },
        { key: 'name', title: 'Name' },
        { key: 'age', title: 'Age' },
        { key: 'actions', title: 'Actions' },
        { key: "sys_name", title: "sysName", width: 200, ellipsis: { "tooltip": true } }
    ];
```
在 template 中打印 {{ column }}，title 不见了：
`{ "key": "sys_name", "width": 200, "ellipsis": { "tooltip": true } }` 

您就不能多复制一个 `_title`，将其转为 jsx 么，不一定要动原 title 属性。

**Comment by fudiwei** [comment]
这个 `title` 是要传给 NDataTableColumn 的。

> https://www.naiveui.com/zh-CN/light/components/data-table#DataTable-Props
> 
> ![image](https://github.com/fudiwei/x.naive-ui/assets/18504146/f0d3c0af-96cf-40ee-af6a-17afc6d2c5f8)

**Comment by transtone** [comment]
> 这个 `title` 是要传给 NDataTableColumn 的。
> 
> > https://www.naiveui.com/zh-CN/light/components/data-table#DataTable-Props
> > ![image](https://private-user-images.githubusercontent.com/18504146/324242018-f0d3c0af-96cf-40ee-af6a-17afc6d2c5f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTE0ODgsIm5iZiI6MTcxNDM5MTE4OCwicGF0aCI6Ii8xODUwNDE0Ni8zMjQyNDIwMTgtZjBkM2MwYWYtOTZjZi00MGVlLWFmNmEtMTdhZmM2ZDJjNWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExNDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZWQyODRlYmVjN2UyNWExMzZjZjZhMWEyZWQwMTg4Yzc1N2YyYzI5NmY0ZWIxMDY0MmM5OWIyZTU5N2M3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E8DEOSrPKJTsm7xF_LMyDLjSI931o-pnrgSSwY3lpUY)



没看懂上面👆的意思。 column 的数据中是包含 title 的，需要怎么传？
```vue
<template>
 <x-n-data-table :columns="columns" :data="data">
      <template #render-column="{ column }">
             {{ column }}
      </template>
    </x-n-data-table>
</template>
<script setup>

    const columns = [
        { type: 'selection' },
        { key: 'no', title: 'NO.' },
        { key: 'name', title: 'Name' },
        { key: 'age', title: 'Age' },
        { key: 'actions', title: 'Actions' },
        { key: "sys_name", title: "sysName", width: 200, ellipsis: { "tooltip": true } }
    ];

    const data = [
        { key: 1, name: 'Athos', age: 20 },
        { key: 2, name: 'Porthos', age: 19 },
        { key: 3, name: 'Aramis', age: 18 }
    ];
</script>
```
