### ISSUE TITLE
1.17.0 版本中，data-table 的 render-cell 插槽不起作用

### ISSUE THREAD

**Issue by Cat7373** [fudiwei/x.naive-ui#9]
### 代码（pug）
<img width="757" alt="iShot_2024-05-13_15 06 47" src="https://github.com/fudiwei/x.naive-ui/assets/9296576/b50b78b7-0f2f-4eef-9e65-7e4582f847cd">

### 0.16.1 中的效果
![iShot_2024-05-13_15 07 39](https://github.com/fudiwei/x.naive-ui/assets/9296576/49ffae82-f8cd-4440-9672-23674527311c)

### 0.17.0 中的效果
![iShot_2024-05-13_15 06 54](https://github.com/fudiwei/x.naive-ui/assets/9296576/8622903a-73b3-4691-97f2-be53cdaa26a9)

### 其他尝试
1. 试过不设置 x-n-data-table-column 的 key，每个字段渲染出来的均为空白
2. 试过 x-n-data-table-column 的 key 设置为不存在的字段，每个字段渲染出来的均为空白

**Comment by fudiwei** [comment]
Fixed on [v0.17.1](https://www.npmjs.com/package/@skit/x.naive-ui/v/0.17.1).

**Comment by Cat7373** [comment]
确认修复
